use anyhow::{bail, Context, Result};
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

const INF_TEMPLATE: &str = r#"; WinUSB driver for AT32F405 ROM DFU bootloader
; Generated by monsgeek-unbrick

[Version]
Signature   = "$Windows NT$"
Class       = USBDevice
ClassGUID   = {88BAE032-5A81-49f0-BC3D-A4FF138216D6}
Provider    = %ManufacturerName%
CatalogFile = monsgeek-dfu.cat
DriverVer   = 01/01/2025,1.0.0.0

[Manufacturer]
%ManufacturerName% = Standard,NTamd64

[Standard.NTamd64]
%DeviceName% = USB_Install, USB\VID_2E3C&PID_DF11

[USB_Install]
Include = winusb.inf
Needs   = WINUSB.NT

[USB_Install.Services]
Include = winusb.inf
Needs   = WINUSB.NT.Services

[USB_Install.HW]
AddReg = Dev_AddReg

[Dev_AddReg]
HKR,,DeviceInterfaceGUIDs,0x10000,"{DEE824EF-729B-4A0E-9C14-B7117D33A817}"

[Strings]
ManufacturerName = "Artery Technology"
DeviceName       = "AT32F405 DFU (MonsGeek Recovery)"
"#;

/// Install the WinUSB driver for the AT32F405 DFU device via pnputil.
pub fn install_winusb_driver() -> Result<()> {
    let temp_dir = get_temp_dir()?;
    std::fs::create_dir_all(&temp_dir)
        .with_context(|| format!("failed to create {}", temp_dir.display()))?;

    let inf_path = temp_dir.join("monsgeek-dfu.inf");
    let mut f = std::fs::File::create(&inf_path)?;
    f.write_all(INF_TEMPLATE.as_bytes())?;
    drop(f);

    println!("Installing WinUSB driver from {}...", inf_path.display());

    let output = Command::new("pnputil")
        .args(["/add-driver", &inf_path.to_string_lossy(), "/install"])
        .output()
        .context("failed to run pnputil — is this running as administrator?")?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    if !output.status.success() {
        println!("pnputil stdout: {stdout}");
        println!("pnputil stderr: {stderr}");
        bail!(
            "pnputil failed with exit code {}. \
             Make sure you are running as administrator.",
            output.status
        );
    }

    println!("Driver installed successfully.");
    if stdout.contains("restart") || stderr.contains("restart") {
        println!("NOTE: You may need to unplug and replug the device.");
    }

    Ok(())
}

fn get_temp_dir() -> Result<PathBuf> {
    let temp = std::env::var("TEMP")
        .or_else(|_| std::env::var("TMP"))
        .unwrap_or_else(|_| r"C:\Windows\Temp".to_string());
    Ok(PathBuf::from(temp).join("monsgeek-unbrick"))
}
